apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: (backend|archive|cron|queue|queue-calculate-cameras|schedule|analytic-events|analytic-statistics|queue-controller-webhooks)
  path: analytics-env.yaml
