---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: traefik-traefik-v2
    app.kubernetes.io/name: traefik
  name: strip-prefix-iframe
  namespace: vsaas-vms
spec:
  stripPrefix:
    prefixes:
      - /wb/iframe
    forceSlash: true
