apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: "apps"
    version: v1
    # kind: (Deployment|DaemonSet|StatefulSet)
    kind: (DaemonSet)
    name: (.*)
  path: tolerations.yaml
