---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: analytic-events
    app.kubernetes.io/component: analytic-events
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas
  name: analytic-events
  namespace: vms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: analytic-events
      app.kubernetes.io/component: analytic-events
      app.kubernetes.io/part-of: vms
      global-app-name: vsaas
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytic-events
        app.kubernetes.io/component: analytic-events
        app.kubernetes.io/part-of: vms
        global-app-name: vsaas
    spec:
      securityContext:
        runAsUser: 33
      containers:
        - name: analytic-events
          args:
            - php
            - artisan
            - orchestrator:socket:connect
          envFrom:
            - configMapRef:
                name: vms-backend-env
          image: download.aipix.ai:8443/vms-backend/release:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/www/api/storage/oauth-private.key
              name: vms-backend-oauth
              readOnly: true
              subPath: oauth-private.key
            - mountPath: /var/www/api/storage/oauth-public.key
              name: vms-backend-oauth
              readOnly: true
              subPath: oauth-public.key
            - mountPath: /var/www/api/storage/file.key
              name: vms-backend-oauth
              readOnly: true
              subPath: file.key
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
      imagePullSecrets:
        - name: download-aipix-ai
      hostname: analytic-events
      restartPolicy: Always
      volumes:
        - name: vms-backend-oauth
          secret:
            secretName: vms-backend-oauth
