apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: mediaserver
    app.kubernetes.io/component: mediaserver
    app.kubernetes.io/part-of: mediaserver
    global-app-name: vsaas
  name: mediaserver
  namespace: vsaas-ms
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mediaserver
      app.kubernetes.io/component: mediaserver
      app.kubernetes.io/part-of: mediaserver
      global-app-name: vsaas
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mediaserver
        app.kubernetes.io/component: mediaserver
        app.kubernetes.io/part-of: mediaserver
        global-app-name: vsaas
    spec:
      tolerations:
      - key: mediaserver
        operator: Exists
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: mediaserver
                operator: In
                values:
                - "true"
      hostNetwork: true
      containers:
      - name: mediaserver
        image: download.aipix.ai:8443/media-server/release:latest
        imagePullPolicy: Always
        args: 
        - /bin/sh
        - -c 
        - >
           export $(grep -vE "^(#.*|\s*)$" /opt/aipix/media-server/.env);
           echo LICENSE_SOURCE=${LICENSE_SOURCE} >> ~/.bashrc;
           /opt/aipix/media-server/media-server -c /opt/aipix/media-server/media-server.ini
           -L ${LICENSE_SOURCE} -V4
           2>/var/log/media-server/media-server.err
           1>/var/log/media-server/media-server.log
        volumeMounts:
        - name: media-server-ini
          mountPath: /opt/aipix/media-server/media-server.ini
          readOnly: true
        - name: media-server-nodes
          mountPath: /opt/aipix/media-server/media-server.nodes
          readOnly: true
        - name: media-server-env
          mountPath: /opt/aipix/media-server/.env
          readOnly: true
        - name: fstab
          mountPath: /etc/fstab
          readOnly: true
        - name: machine-id
          mountPath: /etc/machine-id
          readOnly: true
        - name: licenses
          mountPath: /etc/aipix/media-server
        - name: ms-key-pem
          mountPath: /opt/ssl/key.pem
          subPath: key.pem
          readOnly: true
        - name: ms-cert-pem
          mountPath: /opt/ssl/cert.pem
          subPath: cert.pem
          readOnly: true
        - name: streams
          mountPath: /opt/aipix/media-server/streams
        - name: storage
          mountPath: /storage
        resources:
          limits:
            cpu: "6"
            memory: 4Gi
          requests:
            cpu: "200m"
            memory: 200Mi
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      hostname: mediaserver
      imagePullSecrets:
      - name: download-aipix-ai
      volumes:
      - name: media-server-ini
        hostPath:
          path: /opt/mediaserver/configs/media-server.ini
      - name: media-server-nodes
        hostPath:
          path: /opt/mediaserver/configs/media-server.nodes
      - name: media-server-env
        hostPath:
          path: /opt/mediaserver/configs/.env
      - name: fstab
        hostPath:
          path: /etc/fstab
      - name: machine-id
        hostPath:
          path: /etc/machine-id
      - name: licenses
        hostPath:
          path: /opt/mediaserver/licenses
      - name: ms-key-pem
        secret:
          secretName: ms-key-pem
      - name: ms-cert-pem
        secret:
          secretName: ms-cert-pem
      - name: streams
        hostPath:
          path: /opt/mediaserver/streams
      - name: storage
        hostPath:
          path: /storage
