apiVersion: v1
kind: Endpoints
metadata:
  name: clickhouse-server
  labels:
    app.kubernetes.io/name: clickhouse-server
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: analytics
    global-app-name: vsaas
subsets:
  - addresses:
      - ip: 192.168.20.131
    ports:
      - name: "http"
        port: 8123
      - name: "client"
        port: 9000

