{
 "title": "MSE Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(mse_inet_bitrate_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MSE version",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    { "expr": "mse_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network & Storage Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "mse_inet_bitrate_bytes{instance=~\"$host\", type=\"in\"}",
     "legendFormat": "Incoming traffic"
    },
    {
     "expr": "mse_inet_bitrate_bytes{instance=~\"$host\", type=\"out\"}",
     "legendFormat": "Outgoing traffic"
    },
    {
     "expr": "mse_storage_bitrate_bytes{instance=~\"$host\", type=\"require\"}",
     "legendFormat": "Required Throughput (storage)"
    },
    {
     "expr": "mse_storage_bitrate_bytes{instance=~\"$host\", type=\"current\"}",
     "legendFormat": "Actual Throughput (storage)"
    }
   ]
  },
  {
   "title": "Stream Load Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mse_stream_state_total{instance=~\"$host\", type=\"active\"}",
     "legendFormat": "Active Streams"
    },
    {
     "expr": "mse_stream_handle_seconds{instance=~\"$host\", type=\"duration\", quantile=\"0.999\"}",
     "legendFormat": "Duration 99.9%"
    },
    {
     "expr": "mse_stream_handle_seconds{instance=~\"$host\", type=\"duration\", quantile=\"0.6\"}",
     "legendFormat": "Duration 60%"
    },
    {
     "expr": "mse_stream_handle_seconds{instance=~\"$host\", type=\"deadline\", quantile=\"0.6\"}",
     "legendFormat": "Deadline 60%"
    },
    {
     "expr": "mse_stream_handle_seconds{instance=~\"$host\", type=\"duration\", quantile=\"0.6\"} \n/ \nignoring(type) (mse_stream_handle_seconds{instance=~\"$host\", type=\"deadline\", quantile=\"0.6\"} > 0)",
     "legendFormat": "Load Average"
    }
   ]
  },
  {
   "title": "Streams Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "mse_stream_state_total{instance=~\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RTSP Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "mse_rtsp_clients_total{instance=~\"$host\"}",
     "legendFormat": "RTSP client: {{type}}"
    },
    {
     "expr": "sum(rate(mse_rtsp_session_disconnects_total{instance=~\"$host\"}[1m])) by (reason, type)",
     "legendFormat": "RTSP disconnect: {{reason}} ({{type}})"
    }
   ]
  },
  {
   "title": "WebRTC sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "mse_webrtc_clients_total{type=\"dvr\", instance=\"$host\"}",
     "legendFormat": "DVR clients"
    },
    {
     "expr": "mse_webrtc_clients_total{type=\"live\", instance=\"$host\"}",
     "legendFormat": "Live clients"
    },
    {
     "expr": "mse_webrtc_dtls_duration_seconds{instance=\"$host\", quantile=\"0.99\"}",
     "legendFormat": "Dtls Latency 99%"
    },
    {
     "expr": "mse_webrtc_dtls_duration_seconds{instance=\"$host\", quantile=\"0.999\"}",
     "legendFormat": "Dtls Latency 99.9%"
    },
    {
     "expr": "mse_webrtc_bind_duration_seconds{instance=\"$host\", quantile=\"0.99\"}",
     "legendFormat": "Bind Latency 99%"
    },
    {
     "expr": "rate(mse_webrtc_dtls_errors_total{instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Dtls Errors"
    },
    {
     "expr": "rate(mse_webrtc_bind_errors_total{instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Bind Errors"
    },
    {
     "expr": "mse_webrtc_srtp_duration_seconds{instance=\"$host\", quantile=\"0.99\"}",
     "legendFormat": "Srtp Latency 99%"
    },
    {
     "expr": "mse_webrtc_srtp_duration_seconds{instance=\"$host\", quantile=\"0.999\"}",
     "legendFormat": "Srtp Latency 99.9%"
    },
    {
     "expr": "mse_webrtc_srtp_errors_total{instance=\"$host\"}",
     "legendFormat": "Srtp Errors"
    },
    {
     "expr": "mse_webrtc_bind_duration_seconds{instance=\"$host\", quantile=\"0.999\"}",
     "legendFormat": "Bind Latency 99.9%"
    }
   ]
  },
  {
   "title": "Web sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "mse_websessions_active_total{instance=~\"$host\"}",
     "legendFormat": "Active: {{type}}"
    },
    {
     "expr": "mse_websessions_deleted_total{instance=\"$host\"}",
     "legendFormat": "Deleted: {{type}}"
    },
    {},
    {
     "expr": "rate(mse_websessions_failed_total{instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Failed: {{type}}"
    },
    {}
   ]
  },
  {
   "title": "API Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(mse_api_request_errors_total{instance=~\"$host\"}[1m])) by (method)",
     "legendFormat": "API failure: {{method}}"
    }
   ]
  },
  {
   "title": "Webhook Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(rate(mse_webhook_failures_total{instance=~\"$host\"}[1m])) by (type)",
     "legendFormat": "Webhook Failures: {{type}}"
    },
    {
     "expr": "sum(mse_webhook_pendings_total{instance=~\"$host\"})",
     "legendFormat": "Webhook Pending"
    }
   ]
  },
  {
   "title": "VFS Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mse_vfs_duration_seconds_count{instance=~\"$host\"}[$__rate_interval])) by (method)",
     "legendFormat": "Ops: {{method}}"
    },
    {
     "expr": "mse_vfs_duration_seconds_sum{instance=~\"$host\"} / mse_vfs_duration_seconds_count{instance=~\"$host\"}",
     "legendFormat": "Latency: {{method}}"
    },
    {
     "expr": "sum(rate(mse_vfs_errors_total{instance=~\"$host\"}[$__rate_interval])) by (method)",
     "legendFormat": "Errors: {{method}}"
    },
    {
     "expr": "sum(mse_vfs_indexes_total{instance=\"$host\"})",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Api & Media Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mse_api_request_duration_seconds_sum{instance=~\"$host\"}[1m])) by (method) / sum(rate(mse_api_request_duration_seconds_count{instance=~\"$host\"}[1m])) by (method)",
     "legendFormat": "API: {{method}}"
    },
    {
     "expr": "sum(rate(mse_media_request_duration_seconds_sum{instance=~\"$host\"}[1m])) by (method) / sum(rate(mse_media_request_duration_seconds_count{instance=~\"$host\"}[1m])) by (method)",
     "legendFormat": "Media: {{method}}"
    }
   ]
  }
 ]
}