---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vgw-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas
  name: vgw-backend
  namespace: vsaas
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: vgw-backend
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: vms
      global-app-name: vsaas
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vgw-backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: vms
        global-app-name: vsaas
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: vgw-backend
                  app.kubernetes.io/component: backend
                  app.kubernetes.io/part-of: vms
                  global-app-name: vsaas
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
        - name: vgw-backend
          args:
          - php
          - /var/www/api/artisan
          - octane:start
          - --port=8080
          - --host=0.0.0.0
          - --task-workers=2
          - --max-requests=1000
          envFrom:
            - configMapRef:
                name: vms-backend-env
          image: download.aipix.ai:8443/vms-backend/release:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/run/php/
              name: run-php
            - mountPath: /var/www/api/storage/oauth-private.key
              name: vms-backend-oauth
              readOnly: true
              subPath: oauth-private.key
            - mountPath: /var/www/api/storage/oauth-public.key
              name: vms-backend-oauth
              readOnly: true
              subPath: oauth-public.key
            - mountPath: /var/www/api/storage/file.key
              name: vms-backend-oauth
              readOnly: true
              subPath: file.key
          resources:
            requests:
              cpu: 80m
              memory: 400Mi
      imagePullSecrets:
        - name: download-aipix-ai
      hostname: vgw-backend
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: run-php
      - name: vms-backend-oauth
        secret:
          secretName: vms-backend-oauth
