---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: reverse-proxy
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas
  name: nginx
  namespace: vms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/component: reverse-proxy
      app.kubernetes.io/part-of: vms
      global-app-name: vsaas
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/component: reverse-proxy
        app.kubernetes.io/part-of: vms
        global-app-name: vsaas
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: nginx
                  app.kubernetes.io/component: reverse-proxy
                  app.kubernetes.io/part-of: vms
                  global-app-name: vsaas
              topologyKey: kubernetes.io/hostname
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          volumeMounts:
            - name: vms-nginx-cert
              readOnly: true
              mountPath: /opt/ssl/
            - name: vms-nginx-conf
              readOnly: true
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: vms-nginx-base-conf
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx-base.conf
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: 443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /admin/
              port: 443
            periodSeconds: 5
          resources:
            requests:
              cpu: 5m
              memory: 35Mi
      hostname: nginx
      restartPolicy: Always
      volumes:
        - name: vms-nginx-cert
          secret:
            secretName: vms-nginx-cert
        - name: vms-nginx-conf
          configMap:
            name: vms-nginx-conf
        - name: vms-nginx-base-conf
          configMap:
            name: vms-nginx-base-conf
