{
 "title": "Application logs via stdout",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "container",
    "query": {}
   },
   { "name": "search", "label": "Regex Search" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total ERRORs and ALERTs",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "count(rate({job=\"vsaas\",container=~\"$container\", namespace=\"$namespace\",level=~`ERROR|ALERT`} [$__auto]))"
      }
     ]
    },
    {
     "title": "Log Level Distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 17, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by(level) (count_over_time({job=\"vsaas\", namespace=\"$namespace\", container=~\"${container:pipe}\"} | json | label_format level=detected_level [$__range]))"
      }
     ]
    },
    {
     "title": "Filter by level",
     "type": "table",
     "gridPos": { "h": 8, "w": 2, "x": 22, "y": 1 },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({job=\"vsaas\", container=~\"${container:pipe}\"} | json | label_format level=detected_level [$__range]))"
      }
     ]
    },
    {
     "title": "Messages Amount",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({job=\"vsaas\", container=~\"${container:pipe}\"} | json | label_format level=detected_level [$__range]))"
      }
     ]
    }
   ]
  },
  { "title": "Stdout logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Messages",
   "type": "logs",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vsaas\", namespace=\"$namespace\", container=~\"${container:pipe}\"} | json |~ `(?i)${search:raw}` | line_format `{{.level}} {{.service_name}} {{.trace_trace_id }}| {{.message}}` | label_format level=detected_level"
    }
   ]
  }
 ]
}