{
 "title": "Applications Logs",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": "label_values(host)" },
   { "name": "search", "label": "search" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Volume",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({host=~\"${host:pipe}\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "by service per 1m",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_over_time({host=~\"$host:pipe\"}[1m])\n",
       "legendFormat": "{{host}}",
       "maxLines": 5000
      }
     ]
    },
    {
     "title": "ERRORS per 1 min",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_over_time({job=\"syslog\"}|~\"ERROR\"[1m])",
       "legendFormat": "{{host}}",
       "maxLines": 2000
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 43, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{host=~\"$host\",job=\"syslog\"}|json|~\"(?i)${search:raw}\"| line_format \"{{.host}} {{.log}}\"",
     "maxLines": 2000
    }
   ]
  }
 ]
}