apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: apps
      version: v1
      kind: (StatefulSet|Deployment)
      name: push1st
    path: push1st-devices-app.yaml
