apiVersion: v1
kind: Service
metadata:
  name: syslog
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: fluent-bit
  ports:
  - name: syslog
    protocol: UDP
    port: 5140
    targetPort: 5140