---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: analytics-worker
    app.kubernetes.io/component: analytics-worker
    app.kubernetes.io/part-of: analytics
    global-app-name: vsaas
  name: analytics-worker
  namespace: vsaas-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics-worker
      app.kubernetes.io/component: analytics-worker
      app.kubernetes.io/part-of: analytics
      global-app-name: vsaas
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics-worker
        app.kubernetes.io/component: analytics-worker
        app.kubernetes.io/part-of: analytics
        global-app-name: vsaas
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: analytics
                operator: In
                values:
                - "true"
      containers:
        - name: worker
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: ["python"]
          args: ["-m", "app.main"]
          image: download.aipix.ai:8443/analytics-worker/release:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: env-file
              mountPath: /analytics-worker/.env
              subPath: .env
              readOnly: true
          resources:
            requests:
              cpu: "200m"
              memory: 200Mi
        - name: celery
          command: ["celery"]
          args:
            - -A
            - app.main
            - worker
            - --loglevel=INFO
            - --max-tasks-per-child=1
          image: download.aipix.ai:8443/analytics-worker/release:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: env-file
              mountPath: /analytics-worker/.env
              subPath: .env
              readOnly: true
          resources:
            requests:
              cpu: "8"
              memory: 6Gi
        - name: redis-server
          image: redis:alpine
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: 200Mi
        - name: ovms
          args: [
                 "--config_path", "/workspace/model_config.json",
                 "--log_level", "INFO",
                 "--file_system_poll_wait_seconds", "5",
                 "--grpc_workers", "1",
                 "--sequence_cleaner_poll_wait_minutes", "0",
                 "--port", "8080",
                 "--rest_port", "8081"]
          image: download.aipix.ai:8443/analytics-ovms/release:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: grpc
          - containerPort: 8081
            name: rest
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: rest
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /v2/health/ready
              port: rest
          resources:
            requests:
              cpu: "2"
              memory: 8Gi
      restartPolicy: Always
      hostname: analytics-worker
      imagePullSecrets:
        - name: download-aipix-ai
      volumes:
        - name: env-file
          configMap:
            name: analytics-worker-cm
