{
 "title": "rtpEngine",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values({app_kubernetes_io_name=\"rtpengine-exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sessions",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtpengine_sessions{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Transcoded Media",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtpengine_transcoded_media{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Media Streams",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtpengine_mediastreams{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Packet Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtpengine_packet_rate{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtpengine_byte_rate{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtpengine_error_rate{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "rtpengine status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rtpengine_up{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "uptime,sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtpengine_uptime_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average call duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtpengine_call_duration_avg{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total calls duration squared",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtpengine_call_duration2_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stddev call duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rtpengine_call_duration_stddev{instance=\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total relayed bytes by type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rtpengine_bytes_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total closed Sessions by reason",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rtpengine_closed_sessions_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Total managed sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rtpengine_sessions_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of 1-way streams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rtpengine_one_way_sessions_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of streams with no relayed packets",
   "type": "stat",
   "description": "Total number of streams with no relayed packets",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rtpengine_zero_packet_streams_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total relayed packets by type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtpengine_packets_totaln{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total relayed packet errors type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rtpengine_packet_errors_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "MOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of MOS samples",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 320 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(rtpengine_mos_samples_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MOS Total",
     "type": "stat",
     "description": "Sum of all MOS values sampled",
     "gridPos": { "h": 8, "w": 4, "x": 5, "y": 320 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(rtpengine_mos_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "rtpengine_mos_stddev",
     "type": "timeseries",
     "description": "Stddev of all MOS values sampled",
     "gridPos": { "h": 8, "w": 13, "x": 9, "y": 320 },
     "targets": [
      {
       "expr": "rtpengine_mos_stddev{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "rtpengine_mos_avg",
     "type": "timeseries",
     "description": "Average of all MOS values sampled",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 443 },
     "targets": [
      {
       "expr": "rtpengine_mos_avg{instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MOS2 Total",
     "type": "timeseries",
     "description": "Sum of all MOS square values sampled",
     "gridPos": { "h": 8, "w": 13, "x": 9, "y": 443 },
     "targets": [
      {
       "expr": "rtpengine_mos2_total{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "VoIP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets lost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 321 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rtpengine_packets_lost{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Out-of-order RTP packets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 321 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rtpengine_rtp_reordered{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RTP sequence skips",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 321 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rtpengine_rtp_skips{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum of all jitter",
     "type": "stat",
     "description": "Sum of all jitter (reported) values sampled",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 321 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rtpengine_jitter_total{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RTP sequence resets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 321 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rtpengine_rtp_seq_resets{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average of all jitter samples",
     "type": "stat",
     "description": "Average of all jitter (reported) samples",
     "gridPos": { "h": 3, "w": 4, "x": 11, "y": 321 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rtpengine_jitter_avg{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total number of jitter samples",
     "type": "stat",
     "description": "Total number of jitter (reported) samples",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 321 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rtpengine_jitter_samples_total{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duplicate RTP packets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 321 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rtpengine_rtp_duplicates{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used Ports",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "rtpengine_ports_used{instance=\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Free Ports",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 82 },
     "targets": [
      {
       "expr": "rtpengine_ports_free{instance=\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current Ports",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 17, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rtpengine_ports{instance=\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Interface Ports",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "rtpengine_interface_ports{instance=\"$instance\", type!~\"min|max\"}",
       "legendFormat": "{{name}}({{address}}) {{type}}"
      }
     ]
    },
    {
     "title": "Stddev of all MOS values sampled",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 90 },
     "targets": [
      {
       "expr": "rtpengine_interface_mos_stddev{instance=\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Average of all MOS values sampled",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 17, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rtpengine_interface_mos_avg{instance=\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sum of all MOS values sampled",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "rtpengine_interface_mos_total{instance=\"$instance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Proxy Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 157 },
     "targets": [
      {
       "expr": "rtpengine_requests_total{instance=\"$instance\", proxy=\"127.0.0.1\"}",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "Requests duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 157 },
     "targets": [
      {
       "expr": "rtpengine_request_seconds_total{instance=\"$instance\", proxy=\"127.0.0.1\"}",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "Errrr requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
     "targets": [
      {
       "expr": "rtpengine_errors_total{instance=\"$instance\", proxy=\"127.0.0.1\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}