{
 "title": "sip-gw",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Intercom registered",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vgw_sip_usrloc_registered_users",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed calls",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vgw_sip_core_rcv_requests_bye[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Abandoned Calls",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vgw_sip_core_rcv_requests_cancel[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked IPs Quantity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vgw_sip_pike_blocked_ips", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "core",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "INVITE",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vgw_sip_core_rcv_requests_invite",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BYE",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 6, "y": 6 },
     "targets": [
      { "expr": "vgw_sip_core_rcv_requests_bye" }
     ]
    },
    {
     "title": "CANCEL",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 13, "y": 6 },
     "targets": [
      {
       "expr": "vgw_sip_core_rcv_requests_cancel"
      }
     ]
    },
    {
     "title": "core_bad_URIs_rcvd",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
     "targets": [
      { "expr": "vgw_sip_core_bad_URIs_rcvd" }
     ]
    },
    {
     "title": "vgw_sip_core_fwd_requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 6, "y": 12 },
     "targets": [
      { "expr": "vgw_sip_core_fwd_requests" }
     ]
    }
   ]
  },
  {
   "title": "dns",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true
  },
  {
   "title": "http_async_client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "http statistics",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "vgw_sip_http_async_client_errors"
      },
      {
       "expr": "vgw_sip_http_async_client_replies"
      },
      {
       "expr": "vgw_sip_http_async_client_requests"
      },
      {
       "expr": "vgw_sip_http_async_client_timeouts"
      }
     ]
    }
   ]
  },
  {
   "title": "http_client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "pike",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocked IP Quantity ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "targets": [
      { "expr": "vgw_sip_pike_blocked_ips" }
     ]
    }
   ]
  },
  {
   "title": "registrar",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Registrations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "vgw_sip_registrar_accepted_regs",
       "legendFormat": "__auto"
      },
      {
       "expr": "vgw_sip_registrar_rejected_regs",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "shared memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "mem_fragments",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 24 },
     "targets": [
      { "expr": "vgw_sip_shmem_fragments" }
     ]
    },
    {
     "title": "memory metrics",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 24 },
     "targets": [
      { "expr": "vgw_sip_shmem_total_size" },
      { "expr": "vgw_sip_shmem_used_size" }
     ]
    }
   ]
  },
  {
   "title": "sl",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "tcp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "tcp metrics",
     "type": "timeseries",
     "gridPos": { "h": 21, "w": 23, "x": 0, "y": 14 },
     "targets": [
      { "expr": "vgw_sip_tcp_con_reset" },
      { "expr": "vgw_sip_tcp_con_timeout" },
      { "expr": "vgw_sip_tcp_connect_failed" },
      { "expr": "vgw_sip_tcp_connect_success" },
      {
       "expr": "vgw_sip_tcp_current_opened_connections"
      },
      {
       "expr": "vgw_sip_tcp_current_write_queue_size"
      },
      { "expr": "vgw_sip_tcp_local_reject" },
      { "expr": "vgw_sip_tcp_send_timeout" },
      { "expr": "vgw_sip_tcp_sendq_full" }
     ]
    }
   ]
  },
  {
   "title": "tmx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "vgw_sip_tmx_active_transactions",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "usrloc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "websocket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Dialogs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed_dialogs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "vgw_sip_dialog_processed_dialogs"
      }
     ]
    },
    {
     "title": "Active Dialogss",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      { "expr": "vgw_sip_dialog_active_dialogs" }
     ]
    }
   ]
  }
 ]
}