---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: beanstalkd
    app.kubernetes.io/component: message-broker
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas
  name: beanstalkd
  namespace: vms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: beanstalkd
      app.kubernetes.io/component: message-broker
      app.kubernetes.io/part-of: vms
      global-app-name: vsaas
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: beanstalkd
        app.kubernetes.io/component: message-broker
        app.kubernetes.io/part-of: vms
        global-app-name: vsaas
    spec:
      containers:
        - name: beanstalkd
          # image: schickling/beanstalkd:latest
          image: download.aipix.ai:8443/beanstalkd:1.13
          imagePullPolicy: Always
          command:
            - /usr/bin/beanstalkd
            - -z
            - "524280"
          ports:
            - containerPort: 11300
              name: beanstalkd
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 11300
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
        - name: beanstalkd-exporter
          image: download.aipix.ai:8443/beanstalkd-exporter:2.0.0
          imagePullPolicy: Always
          args:
            - --beanstalkd.systemMetrics=current_connections_count,current_jobs_buried_count,current_waiting_count
            - --beanstalkd.allTubes
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
      hostname: beanstalkd
      restartPolicy: Always
      imagePullSecrets:
        - name: download-aipix-ai