---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: beanstalkd
    app.kubernetes.io/component: message-broker
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas
  name: beanstalkd
  namespace: vms
spec:
  ports:
    - name: "beanstalkd"
      port: 11300
      protocol: TCP
      targetPort: 11300
  selector:
    app.kubernetes.io/name: beanstalkd
    app.kubernetes.io/component: message-broker
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas
