apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: (analytic-.*|archive|backend|ble-service|cron|integration-wb|portal-.*|queue.*|reports|schedule|vgw-backend|controller-.*)
    path: empty-env-list.yaml