---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: metrics-pusher
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: analytics
    global-app-name: vsaas
  name: metrics-pusher
  namespace: vsaas-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-pusher
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/part-of: analytics
      global-app-name: vsaas
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metrics-pusher
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/part-of: analytics
        global-app-name: vsaas
    spec:
      containers:
        - name: metrics-pusher
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: metrics-pusher-env
          image: download.aipix.ai:8443/analytics-metrics-pusher/release:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "5m"
              memory: 40Mi
        - name: telegraf
          imagePullPolicy: Always
          image: telegraf:1.27-alpine
          volumeMounts:
            - name: telegraf-conf
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
          resources:
            requests:
              cpu: "5m"
              memory: 40Mi
      restartPolicy: Always
      hostname: metrics-pusher
      imagePullSecrets:
        - name: download-aipix-ai
      volumes:
        - name: telegraf-conf
          configMap:
            name: telegraf-conf
