---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: metrics-pusher
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: analytics
    global-app-name: vsaas
  name: metrics-pusher
  namespace: vsaas-analytics
spec:
  ports:
    - name: "http"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: metrics-pusher
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: analytics
    global-app-name: vsaas
