apiVersion: v1
items:
- apiVersion: ceph.rook.io/v1
  kind: CephFilesystem
  metadata:
    name: myfs
    namespace: rook-ceph
  spec:
    dataPools:
    - erasureCoded:
        codingChunks: 0
        dataChunks: 0
      failureDomain: host
      mirroring: {}
      name: replicated
      parameters:
        compression_mode: none
      quotas: {}
      replicated:
        requireSafeReplicaSize: true
        size: 3
      statusCheck:
        mirror: {}
    metadataPool:
      erasureCoded:
        codingChunks: 0
        dataChunks: 0
      mirroring: {}
      parameters:
        compression_mode: none
      quotas: {}
      replicated:
        requireSafeReplicaSize: true
        size: 3
      statusCheck:
        mirror: {}
    metadataServer:
      activeCount: 1
      activeStandby: true
      livenessProbe: {}
      placement:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rook-ceph-mds
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-mds
            topologyKey: kubernetes.io/hostname
      priorityClassName: system-cluster-critical
      resources: {}
      startupProbe: {}
    preserveFilesystemOnDelete: true
    statusCheck:
      mirror: {}
kind: List
metadata:
  resourceVersion: ""
