---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: tarantool
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: analytics
    global-app-name: vsaas
  name: tarantool
  namespace: vsaas-analytics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs

