---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tarantool
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: analytics
    global-app-name: vsaas
  name: tarantool
  namespace: vsaas-analytics
spec:
  ports:
    - name: "tarantool"
      port: 3301
      protocol: TCP
      targetPort: 3301
  selector:
    app.kubernetes.io/name: tarantool
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: analytics
    global-app-name: vsaas

