{
 "title": "Access Logs",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "traefikInstance", "query": "label_values(instance)" },
   { "name": "statusCodes", "query": "0,2..,3..,4..,5.." },
   { "name": "search", "label": "regex search" }
  ]
 },
 "panels": [
  { "title": "Status Codes Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"traefik-v2\",container=\"traefik\"}[$__interval]))",
     "legendFormat": "log"
    }
   ]
  },
  {
   "title": "2XX Statuses Rate per Minute",
   "type": "gauge",
   "description": "Rate of 2XX per minute",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=\"200\"}[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "3XX Statuses Rate per Minute",
   "type": "gauge",
   "description": "Rate of 3XX statuses per 1m",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"3..\"}[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "4XX Statuses per Minute",
   "type": "gauge",
   "description": "Rate of 4XX statuses per 1m",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"4..\"}[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "5XX codes per Minute",
   "type": "gauge",
   "description": "Rate of 5XX statuses per 1m",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "percent of serrver erros",
   "type": "gauge",
   "description": "Total requests to 5XX error",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total{code=~\"5..\"}) / sum(traefik_entrypoint_requests_total) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Access Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Access Logs",
   "type": "logs",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{container=\"traefik\",job=\"kubernetes\",namespace=\"traefik-v2\",instance=~\"${traefikInstance:pipe}\"} | json |line_format \"{{.log}}\" | pattern `<ip> - - [<time>] \"<method> <path> <_>\" <status> <_> \"<_>\" \"<userAgent>\"` | line_format \"{{.log}}\" |~ \"(?i)${search}\" | status =~ \"${statusCodes:pipe}\"",
     "maxLines": 3000
    }
   ]
  }
 ]
}