{
 "title": "analytics-workers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Orchestrator Events Collector Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deployment_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "orchestrator_events_collector",
     "select": [
      [
       { "params": [ "messages_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Orchestrator Stats Processor Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "deployment_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "orchestrator_stats_processor",
     "select": [
      [
       { "params": [ "messages_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker's errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "error_description" ], "type": "tag" },
      { "params": [ "job_uid" ], "type": "tag" },
      { "params": [ "error_code" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analytics_workers_errors",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage by workers, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "deployment_name" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "analytics_workers_resource_usage",
     "select": [
      [
       { "params": [ "cpu_loadavg_percent_1min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage by workers, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analytics_workers_resource_usage",
     "select": [
      [
       { "params": [ "used_percent_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs per worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "$tag_ovms_uid",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "ovms_uid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analytics_workers_jobs",
     "select": [
      [
       { "params": [ "streams_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "alias": "ovms: $tag_ovms_uid, stream: $tag_stream_uid",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "stream_uid" ], "type": "tag" },
      { "params": [ "ovms_uid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analytics_workers_jobs_stats",
     "query": "SELECT mean(\"status\") FROM \"3_month\".\"analytics_workers_jobs_stats\" WHERE (\"deployment_name\"::tag = 'ovms') AND $timeFilter GROUP BY time(10s), \"stream_uid\"::tag",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "alias": "events",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analytics_workers_events",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events by Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "alias": "ip: $tag_ip, analytics_type: $tag_analytics_type",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "analytics_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analytics_workers_events",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events by Analytics Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "alias": "$tag_analytics_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "analytics_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "analytics_workers_events",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}