{
 "title": "Models Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "model_name",
    "query": {
     "query": "label_values(ovms_requests_success, name)"
    }
   },
   {
    "name": "model_version",
    "query": {
     "query": "label_values(ovms_requests_success, version)"
    }
   },
   { "name": "interface", "query": "gRPC,REST" }
  ]
 },
 "panels": [
  {
   "title": "Service Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput [RPS]",
   "type": "timeseries",
   "description": "Number of requests being processed by the model per second",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(job) (rate(ovms_requests_success{method=~\"ModelInfer|Predict\", name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m]))",
     "legendFormat": "RPS {{job}}"
    }
   ]
  },
  {
   "title": "Throughput [RPS]",
   "type": "gauge",
   "description": "Number of requests being processed by the model per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(ovms_requests_success{method=~\"ModelInfer|Predict\", name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m]))",
     "legendFormat": "RPS {{job}}"
    }
   ]
  },
  {
   "title": "Mean Latency [ms]",
   "type": "gauge",
   "description": "Latency averaged across all requests processed by the model in a certain timeframe",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum by(job)  (rate(ovms_request_time_us_sum{name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m])) / 1000) / sum by(job) (rate(ovms_request_time_us_count{name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m])))",
     "legendFormat": "mean_latency {{job}}"
    }
   ]
  },
  {
   "title": "Latency Quantile [ms] (q=0.75, 0.90, 0.99)",
   "type": "timeseries",
   "description": "Value of latency for quantiles [0.75, 0.90, 0.99], meaning the latency that has NOT been exceeded by 75%, 90% and 99% of the requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(ovms_request_time_us_bucket{name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m]))) / 1000",
     "legendFormat": "quantile==0.75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(ovms_request_time_us_bucket{name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m]))) / 1000",
     "legendFormat": "quantile==0.90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(ovms_request_time_us_bucket{name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m]))) / 1000",
     "legendFormat": "quantile==0.99"
    }
   ]
  },
  {
   "title": "Latency Distribution [%]",
   "type": "bargauge",
   "description": "Distribution of the latencies across the buckets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (le) (rate(ovms_request_time_us_bucket{name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m])) / scalar((sum by (le) (rate(ovms_request_time_us_count{name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m])))) * 100)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Apdex Score ( t1=67ms, t2=218 ms )",
   "type": "timeseries",
   "description": "Apdex score calculated as:\n(num_samples < 0,t1>  +  num_samples < t1,t2> / 2) / num_samples",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "(\n  sum(rate(ovms_request_time_us_bucket{le=\"67466\", name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m])) +\n  ((sum(rate(ovms_request_time_us_bucket{le=\"218591\", name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m])) - \n  sum(rate(ovms_request_time_us_bucket{le=\"67466\", name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m]))) / 2)\n) / sum(rate(ovms_request_time_us_count{name=~\"$model_name\", version=~\"$model_version\", interface=\"$interface\"}[1m]))",
     "legendFormat": "apdex_score"
    }
   ]
  },
  {
   "title": "Number of replicas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"pod\", ovms_streams{name=~\"$model_name\", version=~\"$model_version\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean Inference Time [ms]",
   "type": "gauge",
   "description": "Time of inference execution, averaged across all requests processed by the model in a certain timeframe",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(ovms_inference_time_us_sum{name=~\"$model_name\", version=~\"$model_version\"}[1m])) / 1000) / sum(rate(ovms_inference_time_us_count{name=~\"$model_name\", version=~\"$model_version\"}[1m]))",
     "legendFormat": "inference_time"
    }
   ]
  },
  {
   "title": "Mean Time of Request Waiting For Inference [ms]",
   "type": "gauge",
   "description": "Time of a request waiting for the inference execution, averaged across all requests processed by the model in a certain timeframe",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(ovms_wait_for_infer_req_time_us_sum{name=~\"$model_name\", version=~\"$model_version\"}[1m])) / 1000) / sum(rate(ovms_wait_for_infer_req_time_us_count{name=~\"$model_name\", version=~\"$model_version\"}[1m]))",
     "legendFormat": "queue_time"
    }
   ]
  },
  {
   "title": "Currently Processed Requests",
   "type": "gauge",
   "description": "Number of requests being currently processed by the model server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ovms_current_requests{name=~\"$model_name\", version=~\"$model_version\"})",
     "legendFormat": "active_requests"
    }
   ]
  }
 ]
}