---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mysql-server
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas
  name: mysql-server
  namespace: vms
spec:
  ports:
    - name: "mysql"
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app.kubernetes.io/name: mysql-server
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas

---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: vms
  labels:
    app.kubernetes.io/name: mysql-server
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas
spec:
  selector:
    app.kubernetes.io/name: mysql-server
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas
  ports:
  - name: "mysqld-exporter"
    port: 9104
    protocol: TCP
    targetPort: 9104
