---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio-data-1
  name: minio-data-1
  namespace: minio-ha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio-data-2
  name: minio-data-2
  namespace: minio-ha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage

