---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: push1st-sa
  namespace: vms

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: push1st-role
  namespace: vms
rules:
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: push1st-binding
  namespace: vms
subjects:
- kind: ServiceAccount
  name: push1st-sa
  namespace: vms
roleRef:
  kind: Role
  name: push1st-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: push1st
    app.kubernetes.io/component: message-broker
    app.kubernetes.io/part-of: vms
    global-app-name: vsaas
  name: push1st
  namespace: vms
spec:
  serviceName: push1st-cluster
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: push1st
      app.kubernetes.io/component: message-broker
      app.kubernetes.io/part-of: vms
      global-app-name: vsaas
  template:
    metadata:
      labels:
        app.kubernetes.io/name: push1st
        app.kubernetes.io/component: message-broker
        app.kubernetes.io/part-of: vms
        global-app-name: vsaas
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: push1st
              topologyKey: kubernetes.io/hostname
      serviceAccountName: push1st-sa
      containers:
        - name: push1st
          args:
            - /opt/push1st/push1st
            - -c
            - /opt/push1st/cluster.yml
          image: download.aipix.ai:8443/push1st/release:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6002
              name: api
              protocol: TCP
            - containerPort: 6003
              name: server
              protocol: TCP
            - containerPort: 8002
              name: cluster
              protocol: UDP
          volumeMounts:
            - mountPath: /opt/push1st/apps
              name: apps-volume
            - mountPath: /opt/push1st/cluster.yml
              name: push1st-cluster
              readOnly: true
              subPath: cluster.yml
            - mountPath: /opt/push1st/apps/app.yml
              name: push1st-app
              readOnly: true
              subPath: app.yml
          livenessProbe:
            tcpSocket:
              port: 6002
          readinessProbe:
            tcpSocket:
              port: 6003
            periodSeconds: 5
          resources:
            requests:
              cpu: 20m
              memory: 30Mi
      imagePullSecrets:
        - name: download-aipix-ai
      hostname: push1st
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: apps-volume
      - configMap:
          defaultMode: 420
          name: push1st-cluster
        name: push1st-cluster
      - configMap:
          defaultMode: 420
          name: push1st-app
        name: push1st-app
