apiVersion: v1
kind: Service
metadata:
  name: syslog
  namespace: monitoring
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
spec:
  type: ClusterIP
  ports:
    - name: syslog
      port: 5140
      targetPort: 5140
      protocol: UDP
  selector:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
