---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app.kubernetes.io/instance: traefik-traefik-v2
    app.kubernetes.io/name: traefik
  namespace: minio-single
  name: minio-api
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host (`example.com`)
    services:
    - kind: Service
      name: minio
      port: 9000
